[package]
name = "gq"
version = "0.1.0"
edition = "2021"

[dependencies]
template_types = {path = "../template_types"}
template_macros= {path = "../template_macros"}
serde = { version = "1.0.209", features = ["derive"] }
serde_yml = "0.0.12"
serde_json = "1.0.127"
