[package]
name = "template_types"
version = "0.1.0"
edition = "2021"
[features]
proc_macro=["dep:syn", "dep:proc-macro2"]

[dependencies]
quote = "1"
syn = { version = "2.0.77", features = ["full"], optional=true }
proc-macro2 = { version = "1.0.80", default-features = false, optional=true }